config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      patch '/movies/update_watched_status', to: 'movies#update'
      get '/movies/alphabetize_movies', to: 'movies#index'
      resources :movies, only: [:index, :update]
    end
  end

  resources :users, only: [:new, :create]
  resources :movies, only: [:index, :create, :update, :edit, :show, :destroy]
  resources :tags, only: [:index, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  acts_as_taggable_on :tags
  validates :title, presence: true

  belongs_to :user

  def update_watched_status
    if self.watched == true
      update_attribute(:watched, false)
    else
      update_attribute(:watched, true)
    end
  end

  def self.alphabetize_movies(user)
    where("user_id = #{user.id}")
    .order("movies.title")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates_confirmation_of :password

  has_many :movies 
end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < ApplicationController

  def index
    @movies = Movie.alphabetize_movies(current_user)
    render json: @movies
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update_watched_status
    render json: @movie
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if current_user
      @movies = Movie.where(user: current_user)
      @add_movie = Movie.new
    else
      render file: "public/404"
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      flash[:success] = "Movie successfully added!"
      redirect_to movies_path
    else
      flash[:error] = "Movie title is not valid. Please try adding again."
      redirect_to movies_path
    end
  end

  def update
    movie = Movie.find(params[:id])
    if params[:watched]
      movie.watched = !movie.watched
      movie.save
      redirect_to movies_path
    elsif movie_params[:title]
      movie.update(movie_params)
      redirect_to movies_path
    else
      flash[:error] = "Your movie title is invalid. Please try again."
      redirect_to edit_movie_path
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path
      flash[:success] = "Movie successfully deleteted."
    end
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :note, :user, :user_id, :watched, :tag_list)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to movies_path
    else
      flash[:error] = "Oops! Your login was invalid. Please check your email is valid and passwords match."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You are logged out."
    redirect_to login_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @movies = Movie.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)

      if @user.save
        flash[:success] = "New account successfully created!"
        session[:user_id] = @user.id
        redirect_to movies_path
      else
        flash[:error] = "Oops! Your email or password was invalid. Please try again."
        redirect_to new_user_path
      end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def check_watched_status(status)
    if status == true
      "Watched"
    else
      "Unwatched"
    end
  end

  def watched_button_text(status)
    if status == true
      "Mark as Unwatched"
    else
      "Mark as Watched"
    end
  end

end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/acts_as_taggable_on/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= @movie.title %></div>
<div><%= render @movies %></div>

app/views/home/show.html.erb
<div class="container">
  <div class="jumbotron">
  <h1>Welcome to Movie Vault<h1>
    <p>Don't lose your favorite or must see movies. Save them to watch again or watch later.</p>

    <div class="container">
      <% if (!current_user) %>
      <%= link_to "Log In", "/login", class: "btn btn-primary" %> |
      <%= link_to "Sign Up", "users/new", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'MovieVault', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <div class="navbar-text">Hi, <%= current_user.email %> </div>
          <li><%= link_to "My MovieVault", movies_path %> </li>
            <%= link_to "Sign Out", logout_path, method: :delete, class: "navbar-text" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieVault</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= render "layouts/nav_bar" %>
    <div class="container">
      <% flash.each do |type, message|  %>
        <%= content_tag :div, sanitize(message), class: "alert alert_#{type} admin-flash" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_movie.html.erb
<h2><%= link_to movie.title, movie_path(movie) %></h2>

app/views/movies/edit.html.erb
<div class="container well">
	<h1>Edit This Movie</h1>
	<div id="edit-form">
		<%= form_for (@movie) do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title %><br><br>

			<%= f.label :note, "Note" %>
			<%= f.text_area :note %><br><br>

			<%= f.label :tag_list, 'Tags (separated by commas)' %>
	    <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>

			<%= f.submit "Update Movie", class: "btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1>My MovieVault</h1>

  <div class="add-movie-form text-center well">
  <h2>Add a movie here!</h2>

  <%= form_for (@add_movie) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :note, "Note" %>
    <%= f.text_field :note %>

    <%= f.label :tag_list, 'Tags (separated by commas)' %>
    <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>

    <%= f.submit "Add new movie", class: "btn btn-success" %>
    <% end %>
</div>

<div>
  <h3>Search:</h3>
  <input type="text" class="form-control" id="search-box">
</div>

<div>
    <h3>Filter Status:</h3>
    <%= select("movie", "filter_status", ["All", "Watched", "Unwatched"], selected: "All") %>
</div>

<div id='sort-alpha' class="text-center">
<!-- <h3>Click to Alphabetize List:</h3> -->
  <button id='sort-alpha-button'>Alphabetize this List Now</button>
</div>

<p></p>
<p></p>
  <div id="return-data" class="panel panel-default">
    <h2>All My Movies</h2>
    <table id="movies-list" class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Note</th>
            <th>Tags</th>
            <th>Watched/Unwatched</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody id="movies-table">

        <% current_user.movies.each do |movie| %>
            <tr raw-id="<%= movie.id %>" id="movie-<%= movie.id %>" class="movie <%=check_watched_status(movie.watched)%>" data-status="<%=check_watched_status(movie.watched)%>">
              <td class="movie-title"><%= movie.title %></td>
              <td class="movie-note"><%= movie.note %></td>
              <td class="movie-tag"><%= render movie.tags %></td>
              <td class="movie-status" id="watched-status">
                <button class="watched btn btn-default btn-xs" id="<%= movie.id%>"> <%=watched_button_text(movie.watched)%></button>
              </td>
              <td><%= link_to "Edit", edit_movie_path(movie) %></td>
              <td><%= link_to "Delete", movie_path(movie), method: :delete %></td>
            </tr>
        <% end %>

    </tbody>
    </table>
  </div>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<div><%= render @movie.tags %></div>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @movies %></div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign up here!</h1>
  <div class="signup-form">
    <%= form_for(@user) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email %><br>

      <%= f.label :password %>
      <%= f.password_field :password%><br>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation%><br><br>

      <%= f.submit "Create account", class: "btn btn-success" %>
    <% end %>
  </div>
</div>